### ISSUE TITLE
Reconsider FormatStyle's Codable requirement

### ISSUE THREAD

**Issue by schwa** [apple/swift-foundation#67]
I know FormatStyle in "classic" Foundation (what do we call the other Foundation?) is Codable but it's unclear exactly why it needs to be. The Codable requirement can get in the way of implementing our own FormatStyles that use non-codable types - in particular closures.

Unless there's a compelling reason for swift-foundation's FormatStyle to be codable (quick scan through code didn't find anything) other than "it's Codable in Foundation" might it not be a good idea to remove the requirement?

**Comment by parkera** [comment]
It's `Codable` because we want the format styles to be serializable representations of the intent on how to format something. One use case is a process generating a formattable type + a customized style, sending it to another. The 2nd process may format it at a later time without relaunching the first process. e.g., a widget rendering something just-in-time where the `Date` is constantly changing but the style should remain the same.

I'd also like to point out that we have a high level goal of keeping the API of the package and framework as similar as possible.

**Comment by parkera** [comment]
It's reasonable to suggest that perhaps `Codable` should have been separated from `FormatStyle` as optional, but we didn't go that way because we really did feel like this was the right way to define what the utility of the protocol was.
