### ISSUE TITLE
Is libswiftFoundation available in iOS on device?

### ISSUE THREAD

**Issue by gastaffo** [apple/swift-foundation#688]
Is libswiftFoundation available and packaged with iOS 17/18? If so, how can I choose my app to use the swift version instead of the Obj-C version? If not, do I need to statically link the swift version?

**Comment by jmschonfeld** [comment]
Great question - there is not separate swift-foundation library that is shipped on Apple platforms. Instead this swift-foundation repo is built as a major part of `Foundation.framework` on all Apple platforms. The Foundation framework that is shipped on these platforms will contain all of these swift implementations plus the existing Objective-C/C types that exist today. If you're building an app for iOS, there is no need to do anything special or custom to use these swift implementations, simply `import Foundation` like normal in your Swift code and you'll be getting the Swift implementations of these types.

**Comment by gastaffo** [comment]
Sweet thanks! Do you know what happens if an app uses both Obj-C and Swift? Like will my swift code use the Swift version and Obj-C the Obj-C version? I ask because in some of my frameworks I have Obj-C code that uses swizzling of Foundation that my swift code depends on. 

I've been trying to get a test app to use the swift version to see when a call to say `FileManager` will go through Obj-C and when it will use the Swift version but having trouble getting it to call into the swift version on iOS 18 (Xcode 16 beta) as the test app I'm using seems to still be calling `objc_msgSend`.

**Comment by jmschonfeld** [comment]
In general, our approach is that there should only be one "version" of the implementation of a type and that version should be used wherever the type is present. Without any custom subclassing/swizzling, even when using the Objective-C types (or even the `CoreFoundation` types in some cases where applicable) you'll still end up using the Swift implementations under the hood. You'll still see an `objc_msgSend` in your app since a type like `FileManager` on iOS is still technically an Objective-C class (which we must maintain to be compatible with apps compiled against older SDKs) however the underlying implementation will be the Swift one that you see here in this repo. How this works in practice can vary on a type-by-type basis and may change over time (so it's not an implementation detail to be relied upon). But as an example, some types that are already class cluster types might allocate a special subclass that calls through to the swift implementation:

```objective-c
NSLocale *locale = [NSLocale localeWithLocaleIdentifier:@"en-US"];
NSLog(@"Class: %@", [locale className]); // "Class: _NSSwiftLocale"
```

And other types (like `FileManager`) that are not class clusters may simply call into the Swift implementation of the type for the default implementation of each function (to be used when a subclass doesn't override the function).

**Comment by gastaffo** [comment]
Ok cool that makes sense. Thanks for the info!
