### ISSUE TITLE
`Decimal(sign:exponent:significand:)` causes unexpected sign if `significand` is negative

### ISSUE THREAD

**Issue by EthanHumphrey** [apple/swift-foundation#833]
With the release of iOS 18 Developer Beta 5 and Public Beta 3, my team received reports from customers that all negative values in our app were showing as positives, which led to major confusion.

We narrowed down the issue to a change to the initializer for Decimal: `Decimal(sign:exponent:significand)`. Prior to Beta 5, the sign passed into the initializer would be the sign of the Decimal. Passing `.plus` would result in a positive decimal, and passing `.minus` would result in a negative Decimal. This is regardless of the sign of the significant. In Beta 5, it seems that the sign passed into the init, and the sign of the significand are now negated. This means that passing `.minus` for sign and a negative Decimal for significand results in an unexpectedly positive Decimal value in Beta 5 alone. This behavior does not seem to be explicitly documented.

I created a quick playground to illustrate the issue. Here's the code:

```swift
// Expected Value: 20
// Actual Value: 20
let positiveDecimal = Decimal(sign: .plus, exponent: 1, significand: 2)

// Expected Value: 20
// Actual Value (15.4.0, 16.0 Beta 4): 20
// Actual Value (16.0 Beta 5): -20
let positiveDecimalWithNegativeSignificand = Decimal(sign: .plus, exponent: 1, significand: -2)

// Expected Value: -20
// Actual Value: -20
let negativeDecimal = Decimal(sign: .minus, exponent: 1, significand: 2)

// Expected Value: -20
// Actual Value (15.4.0, 16.0 Beta 4): -20
// Actual Value (16.0 Beta 5): 20
let negativeDecimalWithNegativeSignificand = Decimal(sign: .minus, exponent: 1, significand: -2)
```

I've tracked down the issue to [a PR in the swift-foundation repo](https://github.com/apple/swift-foundation/pull/741/commits/6ccff7b99331095da56fb3188bdd2ecb94096598) from 3 weeks ago, which seems to pull a commit from [the swift-corelibs-foundation repo](https://github.com/apple/swift-corelibs-foundation/pull/3068).

**Comment by vitorll** [comment]
We are facing the same issue and would love to see this fixed by next beta release of iOS 18, is there a way to get this prioritised by the team?

**Comment by oscbyspro** [comment]
While `Decimal` doesn't conform to it, I believe this initializer is supposed to match the one required by [FloatingPoint](https://developer.apple.com/documentation/swift/floatingpoint/init(sign:exponent:significand:)). In that case, the new behavior correctly matches the documented behavior of:

```swift
(sign == .minus ? -1 : 1) * significand * pow(radix, exponent)
```

The new behavior also matches the existing behavior of `Double` for example:

```swift
Double (sign: .minus, exponent: 1, significand: -21) //  42
Decimal(sign: .minus, exponent: 1, significand: -21) // 210 (was: -210)
```

I'm sure you'll get an authoritative answer at some point, but the code for it currently resides in an extension commented as such. So, I suspect that this behavior change is an intentional correction.

https://github.com/apple/swift-foundation/blob/41cbea8b573c14a7f6b8f75c0bb5baec7dced786/Sources/FoundationEssentials/Decimal/Decimal%2BConformances.swift#L36-L39

**Comment by EthanHumphrey** [comment]
I did track down [the original PR on the swift-corelibs-foundation](https://github.com/apple/swift-corelibs-foundation/pull/3068) repo, and I believe you're right that this new behavior is intentional. However, it seems that this is a breaking change to all apps running on iOS 18 Beta 5+ and other platforms bundled with the latest version of Foundation, _not_ just apps that are built with the latest toolchain. As such, I am hoping this change can be reverted for the time being until a better way to roll out this fix can be achieved.

Additionally, the documentation for this specific initializer is vague, which is pointed out in that original PR. I'd argue it implies that the sign given to the initializer will be the sign of the `Decimal`. Unless you have knowledge of the similar `Double` or `FloatingPoint` initializers, you'd have no clue that this isn't the case, especially since Decimal does not conform to `FloatingPoint`.

**Comment by iCharlesHu** [comment]
Hi @EthanHumphrey, thank you for the report. As @oscbyspro mentioned, this is indeed a longstanding bug in both Darwin and the open-source implementation of `NSDecimal`. The implementation of `init(sign: FloatingPointSign, exponent: Int, significand: Decimal)` was initially designed to implement the `FloatingPoint` protocol. The primary reason Decimal cannot fully conform to FloatingPoint is that it lacks a representation for `infinity`, it should otherwise follow the requirements of other methods.

Despite the behavioral changes, we decided to pull in this fix because it addresses a significant issue, and the new implementation is more accurate.

As a workaround, you might consider adding your own initializer to restore the previous behavior:

```swift
public init(sign: FloatingPointSign, exponent: Int, unsignedSignificand: Decimal) {
    self.init(
        _exponent: Int32(exponent) + unsignedSignificand._exponent,
        _length: unsignedSignificand._length,
        _isNegative: sign == .plus ? 0 : 1,
        _isCompact: unsignedSignificand._isCompact,
        _reserved: 0,
        _mantissa: unsignedSignificand._mantissa)
}
```

**Comment by pappalar** [comment]
Breaking change was introduced [here](https://github.com/apple/swift-foundation/commit/892d3c5e478d3cb6796d381d2375977cd137736f#diff-450e677a89402d15b28576d38c2d9495f59c43b22cb9a4252c0be46aac674dc4R238)

While it makes sense to fix a long-standing bug.
It would make more sense to announce it as a breaking change

**Comment by alanzeino** [comment]
I would have hoped if one of Australia's major **_banks_** was in here sounding the alarm maybe someone from Apple would comment on why this wasn't shipped behind a linkedOnOrAfter check. This is a pretty major oversight with unknown but likely widespread consequences.

Apple hasn't even outlined this issue in the [Xcode 16 RC release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes). The closest verbiage related to _any_ of this right now is a hint that there's a crash if you use older `NSDecimal*` APIs (see image below) and that's not even this issue.

The apps I'm supporting ship to about 70m iOS users a month and we have 2 million users on the public beta right now. We're lucky that we caught this and that we have a mechanism to force upgrade users to an audited build (and we're scrambling right now to ship one before you ship 18 on Monday next week).

**But what is the regular developer supposed to do if you haven't even outlined this in the Release Notes?**

<img width="843" alt="Screenshot 2024-09-10 at 9 06 13 PM" src="https://github.com/user-attachments/assets/e9d00dd9-a138-4507-89ca-45ac8deb6f5f">

**Comment by xwu** [comment]
This API is Swift's spelling of the IEEE scaleB operation, which is specified for both binary and decimal floating-point types, so the new behavior _is_ the correct one.

Unfortunately, as with all things, rolling out a fix many years later in an ABI-stable world has its own complications. As others have said, documenting the change would be important, but also breaking existing clients that depend on the prior behavior isn't great. A solution employed in the standard library is defining a custom mangling for the new API and preserving the existing behavior in an ABI-stable but API-unavailable entrypoint--hopefully that can be done by the team here for Swift Foundation (or Apple's internal ingested version of it).

**Comment by alanzeino** [comment]
I don't think anyone is saying that the change isn't needed or shouldn't have been implemented. 

I'd say the contention is:
* According to the ANZ engineers only showed up late in the annual beta cycle in beta 5
* There is no mention of this in the RC Release Notes right now
* There's no way for any developer who doesn't have a blocking force upgrade flow in their software to resolve this for old binaries built with older Base SDKs to address this (because of ABI stability and because this change is default)

At the very least with four days before you ship major releases of your OSes, you would think the Release Notes would state this.

**Comment by parkera** [comment]
We're seeing what options we have for mitigating the impact to customers.

**Comment by alanzeino** [comment]
Thank you Charles!
